console.log (Number('0x77') === 0x77,  "false qani vor numbery talise NaN")
console.log (Number(' 12'),  "false qani  or ka space")
console.log (isNaN(' '),  "false qani vor grvaca space")
console.log (+'' , "0 qani vor da numberi valid falsy arjeqa")
console.log (.1 + .2 == .3  )
console.log (9007199254740992 + 1 == 9007199254740992,  "false qani vor derevs tex ka")
console.log (9007199254740992 + 2 == 9007199254740992,  "hastatun arjex chita kam false kam true")
console.log (0 === +0, "true qani vor nujn bann a" )
console.log (+0 === -0,  "true qani vor nujn bann a")
console.log (1 / '2',  "0.5 mot arjeq qani vor bereluja nujn typi")
console.log (1 / 0  )
console.log (1 / -0  )
console.log (Infinity / 6  )
console.log (Infinity / -256  )
console.log (Infinity / Infinity,  '1')
console.log (0 / 0  )
console.log (+true,  "1 qani vor truthy arjeqa" )
console.log (+false,  "0 qani vor falsy arjeqa")
console.log (+null,  "0 qani vor falsy arjeqa")
console.log (+undefined,  "0 qani vor falsy arjeqa")
console.log (parseInt('.2'),  "2")
console.log (parseInt('077a'),  "77")
console.log (parseInt('0x77a'),  "77")
console.log (parseInt('I’m the best value - said Infinity.'),  "Infinity")
console.log (parseFloat('I’m the best value - said Infinity.'),  "Infinity")
console.log (parseInt('Infinity is the best value!'),  "Infinity")
console.log (parseFloat('Infinity is the best value!'),  "Infinity")
console.log (parseFloat('12.78ff'),  "12.78")