console.log( "" + 1 + 0, '10 qani vor concut a anelu')
console.log( "" - 1 + 0, '-1 qani vor berelua nujn typi hanelu u stanaluja')
console.log( true + false, '1 qani vor bereluja numberi u gumareluja')
console.log( 6 / "3", '2 qani vor bereluja nujn typi')
console.log( "2" * "3", '6 qanimvor bereluja nujn typi')
console.log( 4 + 5 + "px", '9px qani vor gumareluja heto concut  e anelu')
console.log( "$" + 4 + 5, '$45 qani vor concut e anelu')
console.log(2 / 2, '1 qani vor bajanelu a')
console.log( "4" - 2, ' 2 qani vor bereluja nujn typi')
console.log( "4px" - 2, 'NaN qani vor ka px')
console.log( 7 / 0, '')
console.log(  '-9' + 5, '-4 bereluja nujn typi')
console.log( " -9 " - 5, '-14 nujn patcharov')
console.log( null + 1, '1 qani vor nully darnuma 0')
console.log( undefined + 1/1,  'qani vor undefinned darnuma 0')